"""Add nombre and default estado to Usuario

Revision ID: 71d70b0fd53a
Revises: a4f124874c19
Create Date: 2025-05-25 23:08:22.978521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes 


# revision identifiers, used by Alembic.
revision: str = '71d70b0fd53a'
down_revision: Union[str, None] = 'a4f124874c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
